parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $env: '%env(APP_ENV)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
