security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            lazy: true
            custom_authenticator: App\Security\ApiKeyAuthenticator
        admin:
            lazy: true
            provider: user_provider
            custom_authenticator: App\Security\AdminAuthenticator
            logout:
                path: app_logout

    access_control:
         - { path: ^/api, roles: ROLE_API_CLIENT, requires_channel: https }
         - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_API_CLIENT: ROLE_USER
        ROLE_ADMIN: ROLE_USER

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
